# Generated by Django 2.2 on 2020-04-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_created', models.DateTimeField(auto_created=True, null=True)),
                ('job_title', models.CharField(max_length=50, verbose_name='Designation')),
                ('slug', models.SlugField(max_length=40)),
                ('job_location', models.CharField(max_length=50, verbose_name='Job Location')),
                ('experience', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Experience')),
                ('skill', models.CharField(max_length=100, verbose_name='Skills')),
                ('qualification', models.CharField(max_length=100, verbose_name='Qualification')),
                ('min_salary_budget', models.DecimalField(decimal_places=2, help_text='Mention Salary in Annual Packages only', max_digits=10, null=True, verbose_name='Min. Salary Criteria')),
                ('max_salary_budget', models.DecimalField(decimal_places=2, help_text='Mention Salary in Annual Packages only', max_digits=10, null=True, verbose_name='Max. Salary Criteria')),
                ('industry', models.CharField(blank=True, max_length=15, null=True)),
                ('role_category', models.CharField(max_length=50, verbose_name='Role Category')),
                ('employment_type', models.CharField(max_length=100, verbose_name='Employment Type')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='Job Summary')),
                ('job_objective', models.TextField(blank=True, null=True, verbose_name='Job Objectives')),
                ('must_have_skills', models.TextField(blank=True, null=True, verbose_name='Must Have Skills')),
                ('active', models.BooleanField(default=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.CompanyProfile', verbose_name='Company Name')),
            ],
            options={
                'ordering': ['-job_created'],
            },
        ),
    ]
