# Generated by Django 2.2 on 2020-04-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='experience',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='job_location',
            field=models.CharField(max_length=50, null=True, verbose_name='Job Location'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='job_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Designation'),
        ),
    ]
