# Generated by Django 2.2 on 2020-04-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0003_auto_20200419_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='skill',
            field=models.CharField(blank=True, max_length=100, verbose_name='Skills'),
        ),
    ]
