# Generated by Django 2.2 on 2020-04-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0004_auto_20200419_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=40),
        ),
    ]
