# Generated by Django 2.2 on 2020-04-19 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0005_auto_20200419_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='company_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='employer.CompanyProfile', verbose_name='Company Name'),
        ),
    ]
