# Generated by Django 2.2 on 2020-04-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0006_auto_20200419_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Company Name'),
        ),
    ]
