# Generated by Django 2.2 on 2020-04-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_date_created', models.DateTimeField(auto_created=True)),
                ('relevant_industry', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=40)),
                ('company_profile', models.TextField()),
                ('company_location', models.CharField(max_length=50)),
                ('company_website', models.URLField(default=None, verbose_name='Website')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('total_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('company_review', models.DecimalField(blank=True, decimal_places=1, help_text='Rate Company Out Of Five', max_digits=2, null=True)),
            ],
        ),
    ]
