# Generated by Django 2.2.11 on 2020-05-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indeedjobs',
            name='employment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
