# Generated by Django 2.2.11 on 2020-05-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_indeedjobs_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='indeedjobs',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
