# Generated by Django 2.2.11 on 2020-05-23 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_indeedjobs_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indeedjobs',
            name='experience',
        ),
        migrations.AddField(
            model_name='indeedjobs',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
